import {
	affinityLogo,
	affinityLogoHover,
	angularLogo,
	angularLogoHover,
	cssLogo,
	cssLogoHover,
	davinciLogo,
	davinciLogoHover,
	gitLogo,
	gitLogoHover,
	htmlLogo,
	htmlLogoHover,
	jestLogo,
	jestLogoHover,
	jsLogo,
	jsLogoHover,
	lessLogo,
	lessLogoHover,
	linuxLogo,
	linuxLogoHover,
	mysqlLogo,
	mysqlLogoHover,
	npmLogo,
	npmLogoHover,
	pythonLogo,
	pythonLogoHover,
	reactLogo,
	reactLogoHover,
	sassLogo,
	sassLogoHover,
	tsLogo,
	tsLogoHover,
	vsLogo,
	vsLogoHover,
	windowsLogo,
	windowsLogoHover,
	yarnLogo,
	yarnLogoHover,
} from '@shared/assets/index';

interface Props {
	id: number;
	name: string;
	tooltipID?: string;
	defaultIcon: StaticImageData;
	onHoverIcon: StaticImageData;
	height: string;
	width: string;
}

type itemsType = { [key: string]: Props[] };

export const toolsTechItems: itemsType = {
	languages: [
		{
			id: 1,
			name: 'HTML',
			tooltipID: 'html',
			defaultIcon: htmlLogo,
			onHoverIcon: htmlLogoHover,
			height: '46px',
			width: '46px',
		},
		{
			id: 2,
			name: 'CSS',
			tooltipID: 'css',
			defaultIcon: cssLogo,
			onHoverIcon: cssLogoHover,
			height: '65px',
			width: '65px',
		},
		{
			id: 3,
			name: 'LESS',
			tooltipID: 'less',
			defaultIcon: lessLogo,
			onHoverIcon: lessLogoHover,
			height: '65px',
			width: '65px',
		},
		{
			id: 4,
			name: 'SASS',
			tooltipID: 'sass',
			defaultIcon: sassLogo,
			onHoverIcon: sassLogoHover,
			height: '60px',
			width: '60px',
		},
		{
			id: 5,
			name: 'TypeScript',
			tooltipID: 'typescript',
			defaultIcon: tsLogo,
			onHoverIcon: tsLogoHover,
			height: '65px',
			width: '65px',
		},
		{
			id: 6,
			name: 'Javascript',
			tooltipID: 'javascript',
			defaultIcon: jsLogo,
			onHoverIcon: jsLogoHover,
			height: '55px',
			width: '55px',
		},
		{
			id: 7,
			name: 'React',
			tooltipID: 'react',
			defaultIcon: reactLogo,
			onHoverIcon: reactLogoHover,
			height: '55px',
			width: '55px',
		},
		{
			id: 8,
			name: 'Angular',
			tooltipID: 'angular',
			defaultIcon: angularLogo,
			onHoverIcon: angularLogoHover,
			height: '55px',
			width: '55px',
		},
	],
	tools: [
		{
			id: 9,
			name: 'NPM',
			tooltipID: 'npm',
			defaultIcon: npmLogo,
			onHoverIcon: npmLogoHover,
			height: '65px',
			width: '65px',
		},
		{
			id: 10,
			name: 'Yarn',
			tooltipID: 'yarn',
			defaultIcon: yarnLogo,
			onHoverIcon: yarnLogoHover,
			height: '65px',
			width: '65px',
		},
		{
			id: 11,
			name: 'Jest',
			tooltipID: 'jest',
			defaultIcon: jestLogo,
			onHoverIcon: jestLogoHover,
			height: '50px',
			width: '50px',
		},
		{
			id: 12,
			name: 'Git',
			tooltipID: 'git',
			defaultIcon: gitLogo,
			onHoverIcon: gitLogoHover,
			height: '65px',
			width: '65px',
		},
		{
			id: 13,
			name: 'Linux',
			tooltipID: 'linux',
			defaultIcon: linuxLogo,
			onHoverIcon: linuxLogoHover,
			height: '50px',
			width: '50px',
		},
		{
			id: 14,
			name: 'Windows',
			tooltipID: 'windows',
			defaultIcon: windowsLogo,
			onHoverIcon: windowsLogoHover,
			height: '50px',
			width: '50px',
		},
	],
	utils: [
		{
			id: 15,
			name: 'MySQL',
			tooltipID: 'mysql',
			defaultIcon: mysqlLogo,
			onHoverIcon: mysqlLogoHover,
			height: '70px',
			width: '70px',
		},
		{
			id: 16,
			name: 'Affinity',
			tooltipID: 'affinity',
			defaultIcon: affinityLogo,
			onHoverIcon: affinityLogoHover,
			height: '50px',
			width: '50px',
		},
		{
			id: 17,
			name: 'DaVinci Resolve',
			tooltipID: 'davinci',
			defaultIcon: davinciLogo,
			onHoverIcon: davinciLogoHover,
			height: '50px',
			width: '50px',
		},
		{
			id: 18,
			name: 'VS Code',
			tooltipID: 'vscode',
			defaultIcon: vsLogo,
			onHoverIcon: vsLogoHover,
			height: '50px',
			width: '50px',
		},
		{
			id: 19,
			name: 'Python',
			tooltipID: 'python',
			defaultIcon: pythonLogo,
			onHoverIcon: pythonLogoHover,
			height: '55px',
			width: '55px',
		},
	],
};
